// Static site data - replace with Firebase once configured
export const AGENCY_INFO = {
  name: 'The Story Circuit',
  tagline: 'We craft stories that sell.',
  description: 'A creative media agency specialising in premium video production, brand storytelling, and vertical content creation. We help brands stand out through high-production-value visual content.',
  email: 'hello@thestorycircuit.com',
  phone: '+91 96508 66404',
  address: 'Mumbai, India',
  instagram: 'thestorycircuit',
  heroVideo: '/videos/hero.mp4',
  logo: '/logo.png',
};

export const STATS = [
  { number: '30+', label: 'Projects Delivered' },
  { number: '20+', label: 'Happy Clients' },
  { number: '3',   label: 'Years in Production' },
  { number: '5★',  label: 'Client Satisfaction' },
];

export const SERVICES = [
  {
    id: 'social',
    icon: 'social',
    title: 'Social Media Management',
    description: 'End-to-end management of your brand\'s social presence — from posting schedules and community engagement to analytics and platform growth strategies.',
  },
  {
    id: 'strategy',
    icon: 'strategy',
    title: 'Content Strategy',
    description: 'Data-driven content roadmaps tailored to your audience. We plan campaigns that align your brand voice with platform algorithms and real business goals.',
  },
  {
    id: 'creation',
    icon: 'video',
    title: 'Content Creation',
    description: 'Cinematic brand films, high-engagement reels, editorial photography, and scroll-stopping visuals — crafted with premium production quality.',
  },
  {
    id: 'growth',
    icon: 'growth',
    title: 'Brand Growth',
    description: 'Strategic brand positioning, identity refinement, and audience expansion — turning great creative work into measurable growth for your business.',
  },
];

export const PORTFOLIO = [
  {
    id: 'project-1',
    title: 'The Cure — Brand Commercial',
    category: 'video-production',
    categoryLabel: 'Video Production',
    mediaType: 'video',
    src: '/portfolio/cure.mp4',
    thumbnail: '',
    description: 'A high-concept brand advertisement focusing on cinematic lighting, visual metaphors, and a premium editorial style to promote wellness and modern aesthetics.',
    client: 'Cure Wellness',
    year: '2026',
    gridSize: 'large',
    featured: true,
  },
  {
    id: 'project-2',
    title: 'Ragi Foods — Social Promo',
    category: 'video-production',
    categoryLabel: 'Video Production',
    mediaType: 'video',
    src: '/portfolio/ragi.mp4',
    thumbnail: '',
    description: 'High-energy promotional clip showcasing organic Ragi ingredients and healthy recipes, designed to drive social media conversions.',
    client: 'Ragi Nutra',
    year: '2026',
    gridSize: 'wide',
    featured: true,
  },
  {
    id: 'project-3',
    title: 'Eye Focus — Cinematic Sequence',
    category: 'creative-reels',
    categoryLabel: 'Creative Reels',
    mediaType: 'video',
    src: '/portfolio/eye.mp4',
    thumbnail: '',
    description: 'An experimental visual sequence exploring macro lenses, high frame-rate motion tracking, and striking colour grading.',
    client: 'Self-Initiated',
    year: '2025',
    gridSize: 'tall',
    featured: true,
  },
  {
    id: 'project-6',
    title: 'Modern Branding — Editorial',
    category: 'design-photo',
    categoryLabel: 'Design & Photography',
    mediaType: 'image',
    src: '/portfolio/editorial.jpg',
    thumbnail: '/portfolio/editorial.jpg',
    description: 'Art direction and brand styling for a modern design studio, emphasising clean grid structures, elegant typography, and stark contrasts.',
    client: 'Apex Creative',
    year: '2025',
    gridSize: 'std',
    featured: true,
  },
  {
    id: 'project-7',
    title: 'Product Packaging — Visual Design',
    category: 'design-photo',
    categoryLabel: 'Design & Photography',
    mediaType: 'image',
    src: '/portfolio/packaging.jpg',
    thumbnail: '/portfolio/packaging.jpg',
    description: 'Packaging concept and digital render for a luxury cosmetics brand, blending minimalist layouts with rich colour accents.',
    client: 'Aura Cosmetics',
    year: '2026',
    gridSize: 'std',
    featured: false,
  },
  {
    id: 'project-8',
    title: 'Studio Portrait Series',
    category: 'design-photo',
    categoryLabel: 'Design & Photography',
    mediaType: 'image',
    src: '/portfolio/portrait.jpg',
    thumbnail: '/portfolio/portrait.jpg',
    description: 'A striking studio portrait series exploring mood, shadow play, and minimalist composition.',
    client: 'Editorial Magazine',
    year: '2025',
    gridSize: 'std',
    featured: true,
  },
];

export const TESTIMONIALS = [
  {
    id: 't1',
    quote: 'The Story Circuit completely transformed how our brand is perceived online. The video they produced for us stopped scrollers in their tracks — we saw a 3× increase in engagement within the first week.',
    clientName: 'Priya Sharma',
    clientRole: 'Marketing Director',
    clientCompany: 'Cure Wellness',
    initials: 'PS',
    rating: 5,
  },
  {
    id: 't2',
    quote: 'Working with TSC felt effortless. They understood our brand voice immediately and translated it into visuals we never thought possible. Truly a premium creative partner.',
    clientName: 'Arjun Mehta',
    clientRole: 'Founder',
    clientCompany: 'Ragi Nutra',
    initials: 'AM',
    rating: 5,
  },
  {
    id: 't3',
    quote: 'The attention to detail is unreal. From the first brief call to the final delivery, every touchpoint felt high-end. Our Instagram reach doubled the month we started running their content.',
    clientName: 'Sneha Kulkarni',
    clientRole: 'Brand Manager',
    clientCompany: 'Urban Threads',
    initials: 'SK',
    rating: 5,
  },
];

export const FOUNDERS = [
  {
    id: 'f1',
    name: 'Hemang Maheshwari',
    role: 'Creative Director & Co-Founder',
    bio: 'With a background in cinematography and brand strategy, Hemang leads the creative vision at The Story Circuit. Passionate about building visual narratives that go beyond aesthetics and drive real results.',
    photo: null,
    initials: 'HM',
    instagram: 'thestorycircuit',
    linkedin: '#',
  },
  {
    id: 'f2',
    name: 'Co-Founder',
    role: 'Production Head & Co-Founder',
    bio: 'Overseeing every shoot, edit, and delivery — ensuring that The Story Circuit\'s production quality remains consistently world-class from brief to final cut.',
    photo: null,
    initials: '?',
    instagram: '',
    linkedin: '#',
  },
];

export const PACKAGES = [
  {
    id: 'starter',
    name: 'Starter Socials',
    price: '₹49,999',
    period: 'month',
    description: 'Perfect for small businesses looking to establish a strong visual presence online.',
    features: [
      '4 × High-quality vertical reels',
      'Basic graphic templates',
      'Colour grading & sound design',
      '1 × Revision round per reel',
      '10 business day delivery',
    ],
    popular: false,
  },
  {
    id: 'growth',
    name: 'Growth Campaign',
    price: '₹99,999',
    period: 'month',
    description: 'Our most popular plan. For brands that need consistent, high-impact visual campaigns every month.',
    features: [
      '8 × Premium vertical reels / ads',
      '1 × Brand storytelling film',
      'Professional art direction & styling',
      'Custom music licensing & SFX',
      'Unlimited revisions',
      '7-day priority turnaround',
    ],
    popular: true,
  },
  {
    id: 'production',
    name: 'Full-Scale Production',
    price: '₹2,49,999',
    period: 'month',
    description: 'For established brands requiring cinematic commercials, product launches, and editorial shoots.',
    features: [
      '1 × Cinematic brand film / commercial',
      '12 × Social media video assets',
      'Full studio photo shoot (20 final edits)',
      'Scriptwriting, storyboarding & talent',
      '24/7 dedicated creative support',
      'Express delivery available',
    ],
    popular: false,
  },
];
